package com.shy.docverify.config;

public enum ExtractType {
	
	TOBE_TABLENAME, TOBE_ENTITYNAME, TOBE_LOGICALNAME, TOBE_PHYSICALNAME, TOBE_DATATYPE, TOBE_LENGTH, TOBE_NOTNULL, TOBE_PK,
	ASIS_TABLENAME, ASIS_ENTITYNAME, ASIS_LOGICALNAME, ASIS_PHYSICALNAME, ASIS_DATATYPE, ASIS_LENGTH, ASIS_NOTNULL, ASIS_PK;
	
}
